
FROM ubuntu:latest


RUN apt update -y && apt install git -y

RUN apt-get install curl -y && curl -fsSL https://deb.nodesource.com/setup_21.x | bash - &&  apt-get install nodejs -y 

RUN git clone https://github.com/ElianFRagozo/Notas_3.0.git 


WORKDIR /Notas_3.0


RUN npm init -y && npm install -y  && npm install -g http-server -y
 
EXPOSE 3000
 
COPY start.sh /start.sh
RUN chmod +x /start.sh
CMD ["/start.sh"]
